services:
  - type: worker
    name: discord-note-bot_use_ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python NoteBotcommand.py"
    envVars:
      - key: NoteBotDiscordToken
        value: ""